https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [ ]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3,4))

array([[0.45538222, 0.88721317, 0.82153768, 0.21595103],
       [0.87195637, 0.53168564, 0.02020151, 0.03129179],
       [0.08793208, 0.51225591, 0.08768134, 0.23232317]])

In [ ]:
from numpy.random import normal 

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [ ]:
#ndarray,陣列運算
normal_value * 10

array([[ 12.58996287,  15.05783547,   8.69203655, -11.04591528],
       [  6.75457144,  14.75519745,   1.63740728,  -6.23245812],
       [ -3.19942131,  -5.97713143,   7.06584288,  16.16075302]])

In [ ]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([2.52939196, 1.69147181, 1.40500432])